 CREATE TABLE household
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT household_pkey PRIMARY KEY (id)
);

 CREATE TABLE family_member
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    annual_income integer NOT NULL,
    date_of_birth date,
    gender character varying(255) COLLATE pg_catalog."default",
    marital_status character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    occupation_type character varying(255) COLLATE pg_catalog."default",
    household_id bigint,
    spouse_id bigint,
    CONSTRAINT family_member_pkey PRIMARY KEY (id),
    CONSTRAINT family_member_to_house_hold_fk FOREIGN KEY (household_id)
        REFERENCES public.household (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT spouse_to_family_member_fk FOREIGN KEY (spouse_id)
        REFERENCES public.family_member (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE VIEW household_info AS
 SELECT household.id,
    sum(family_member.annual_income) AS total_income,
    count(family_member.id) AS household_size
   FROM household
     JOIN family_member ON household.id = family_member.household_id
  GROUP BY household.id;